# Generated by Django 5.0.6 on 2024-08-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_articlelike_commentlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlelike',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='commentlike',
            old_name='author',
            new_name='user',
        ),
    ]
